### Heavily based on Stanford's CS231n ["Python Numpy Tutorial"](http://cs231n.github.io/python-numpy-tutorial/)

In [1]:
# importing numpy as an object named "np" is the convention:
import numpy as np

In [2]:
# know your version
print(np.__version__)

1.13.3


# Arrays

In [3]:
# Numpy arrays are the basic numpy data type.
# create a 1D numpy array,
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# shape is the most basic attribute of any numpy array
print(a.shape)

(3,)


In [5]:
# subsetting similiar to a list
print(a[0])
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

1
[5 2 3]


In [6]:
# creating a 2D array, a matrix, with a nested list
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print("(2, 3) because of number of rows is %d and number of columns is %d" % b.shape)
# subesetting like subsetting a matrix, remember zero-based indexing!
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
(2, 3) because of number of rows is 2 and number of columns is 3
1 2 4


In [7]:
# create an array of all zeros (the parameter is a tuple specifying the array shape)
a = np.zeros((2,2))
print(a)
print()
# create an array of all ones
b = np.ones((1,2))
print(b)
print()
# create a constant array
c = np.full((2,2), 7)
print(c)
print()
# create a 2x2 identity matrix
d = np.eye(2)
print(d)
print()
# create an array filled with random U(0, 1) values
e = np.random.random((2,2))
print(e)

[[ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.]]

[[7 7]
 [7 7]]

[[ 1.  0.]
 [ 0.  1.]]

[[ 0.54748276  0.54149801]
 [ 0.23089523  0.48119211]]


# Indexing and Slicing

In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print()

# use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b of shape (2, 2)
b = a[:2, 1:3]
print(b)
print()

# a slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]

2
77


In [9]:
# two ways of accessing the data in the middle row of the array.
# mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, "of shape:", row_r1.shape)
print(row_r2, "of shape", row_r2.shape)
print()

# we can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, "of shape", col_r1.shape)
print(col_r2, "of shape", col_r2.shape)

[5 6 7 8] of shape: (4,)
[[5 6 7 8]] of shape (1, 4)

[77  6 10] of shape (3,)
[[77]
 [ 6]
 [10]] of shape (3, 1)


In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
print()

# indexing a numpy array with another array of indices:
# create an array of indices
b = np.array([0, 2, 0, 1])

# select one element from each row of a using the indices in b
print(a[np.arange(4), b])
print()

# mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

# boolean array indexing:
# find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.
bool_idx = (a > 2)
print(bool_idx)
print()

# we use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])
print()

# we can do all of the above in a single concise statement:
print(a[a > 2]) 

[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]

[3 4 5 6]


# Datatypes

In [12]:
# we can choose whether to specify the type of elements in the array or let numpy choose:

# let numpy choose the datatype
x = np.array([1, 2])
print(x.dtype)
print()

x = np.array([1.0, 2.0])
print(x.dtype)
print()

# specify a particular datatype
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64

float64

int64


# Array math

In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# elementwise multiplication by 2 (remember this isn't so simple with a list!)
print(x * 2)
print()

# elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))
print()

# elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
print()

# elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
print()

# elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print()

# elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 2.  4.]
 [ 6.  8.]]

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [14]:
# proper vector/matrix multiplication
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print()

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print()

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print()

219
219

[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]



In [15]:
# no need to use loops for simple aggregation!
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row

10
[4 6]
[3 7]


In [16]:
# transposing a matrix
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# Broadcasting

In [17]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [18]:
# This is better:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)
print()

y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [19]:
# Broadcasting is the best. Magically, v will be added to each row of x:
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


See more [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) for broadcasting rules.

In [20]:
# more broadcasting applications:

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v (3 x 1) and w (1 x 2):
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)
print()

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)
print()

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
print()


# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))
print()

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]

[[2 4 6]
 [5 7 9]]

[[ 5  6  7]
 [ 9 10 11]]

[[ 5  6  7]
 [ 9 10 11]]

[[ 2  4  6]
 [ 8 10 12]]


# More useful stuff

### `stack`, `cocatenate`, `vstack` and `hstack`

In [21]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.stack((a, b)))
print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.concatenate((a, b)))

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]
[1 2 3 2 3 4]


In [22]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
[[1 2]
 [2 3]
 [3 4]]


In [23]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.vstack((a, b)))
print(np.concatenate((a, b), axis = 0))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


### `split`, `vsplit` and `hsplit`

In [24]:
x = np.arange(9.0)
print(np.split(x, 3))

[array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]


In [25]:
x = np.arange(9.0)
print(np.hsplit(x, 3))

[array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]


In [26]:
x = np.arange(16.0).reshape(4, 4)
print(x)
print(np.vsplit(x, 2))

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]]
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.]]), array([[  8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.]])]
