### Heavily based on ["10 Minutes to pandas"](https://pandas.pydata.org/pandas-docs/stable/10min.html)

In [1]:
import pandas as pd

import numpy as np

# Series, DataFrames

In [2]:
# a pandas series is a vector of data, a column
s = pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [3]:
# a DataFrame is a data table, always indexed.
# creating one from a random numpy 2D array (notice the index isn't specified, automatically becomes zero based counter):
df = pd.DataFrame(np.random.randn(6,4), columns = ['A', 'B', 'C', 'D'])
print(df)

          A         B         C         D
0  0.457452 -0.664152  0.148900 -1.038054
1  0.288725 -0.239342 -0.475678  0.286864
2 -0.039578 -0.926392 -0.204653  0.837177
3  0.011836  0.879879  0.872803  0.140642
4 -1.729448  0.605972  1.955143  1.559064
5 -0.367134  1.795627 -0.395771  0.907515


In [4]:
# creating a DataFrame from a very varied dictionary where each key is a column (also see pd.from_dict()):
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1, index = list(range(4)), dtype = 'float32'),
                    'D' : np.array(np.arange(4), dtype = 'int32'),
                    'E' : pd.Categorical(["test", "train", "test", "train"]),
                    'F' : 'foo' })
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  0   test  foo
1  1.0 2013-01-02  1.0  1  train  foo
2  1.0 2013-01-02  1.0  2   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [5]:
# looking at the DataFrame columns types (notice this is a Series!):
print(df2.dtypes)

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


In [6]:
# reading from CSV
df3 = pd.read_csv("https://raw.githubusercontent.com/tau-es-ds/Intro2DS2019/master/datasets/test.csv")
print(df3)

   x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10


# Some info

In [7]:
# get top rows
print(df.head())

          A         B         C         D
0  0.457452 -0.664152  0.148900 -1.038054
1  0.288725 -0.239342 -0.475678  0.286864
2 -0.039578 -0.926392 -0.204653  0.837177
3  0.011836  0.879879  0.872803  0.140642
4 -1.729448  0.605972  1.955143  1.559064


In [8]:
# get bottom rows
print(df.tail(2))

          A         B         C         D
4 -1.729448  0.605972  1.955143  1.559064
5 -0.367134  1.795627 -0.395771  0.907515


In [9]:
# view index
print(df.index)

RangeIndex(start=0, stop=6, step=1)


In [10]:
# view column names
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


In [11]:
# get the underlying numpy matrix
print(df.values)

[[ 0.45745217 -0.66415206  0.14889953 -1.03805361]
 [ 0.28872458 -0.23934212 -0.475678    0.28686389]
 [-0.03957772 -0.92639229 -0.2046532   0.83717659]
 [ 0.01183636  0.8798792   0.87280338  0.14064193]
 [-1.72944766  0.60597246  1.95514299  1.55906351]
 [-0.36713418  1.79562685 -0.39577096  0.90751513]]


In [12]:
# quick statistics summary
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.229691  0.241932  0.316791  0.448868
std    0.787853  1.036442  0.941190  0.886099
min   -1.729448 -0.926392 -0.475678 -1.038054
25%   -0.285245 -0.557950 -0.347992  0.177197
50%   -0.013871  0.183315 -0.027877  0.562020
75%    0.219503  0.811403  0.691827  0.889930
max    0.457452  1.795627  1.955143  1.559064


In [13]:
# transposing a DataFrame
print(df.T)

          0         1         2         3         4         5
A  0.457452  0.288725 -0.039578  0.011836 -1.729448 -0.367134
B -0.664152 -0.239342 -0.926392  0.879879  0.605972  1.795627
C  0.148900 -0.475678 -0.204653  0.872803  1.955143 -0.395771
D -1.038054  0.286864  0.837177  0.140642  1.559064  0.907515


In [14]:
# sorting by column names
print(df.sort_index(axis = 1, ascending = False))

          D         C         B         A
0 -1.038054  0.148900 -0.664152  0.457452
1  0.286864 -0.475678 -0.239342  0.288725
2  0.837177 -0.204653 -0.926392 -0.039578
3  0.140642  0.872803  0.879879  0.011836
4  1.559064  1.955143  0.605972 -1.729448
5  0.907515 -0.395771  1.795627 -0.367134


In [15]:
# sorting by a specific column values
print(df.sort_values(by = 'B'))

          A         B         C         D
2 -0.039578 -0.926392 -0.204653  0.837177
0  0.457452 -0.664152  0.148900 -1.038054
1  0.288725 -0.239342 -0.475678  0.286864
4 -1.729448  0.605972  1.955143  1.559064
3  0.011836  0.879879  0.872803  0.140642
5 -0.367134  1.795627 -0.395771  0.907515


# Selection

In [16]:
# select a specific column (this will give you a Series!) - pandas people do not recommend this, see loc/iloc
print(df['A'])

0    0.457452
1    0.288725
2   -0.039578
3    0.011836
4   -1.729448
5   -0.367134
Name: A, dtype: float64


In [17]:
# slicing rows as in a numpy array - pandas people do not recommend this, see loc/iloc
print(df[0:3])
print(df.T['A':'B'])

          A         B         C         D
0  0.457452 -0.664152  0.148900 -1.038054
1  0.288725 -0.239342 -0.475678  0.286864
2 -0.039578 -0.926392 -0.204653  0.837177
          0         1         2         3         4         5
A  0.457452  0.288725 -0.039578  0.011836 -1.729448 -0.367134
B -0.664152 -0.239342 -0.926392  0.879879  0.605972  1.795627


### Selection by label (`loc`)

In [18]:
# select a specific column, all rows
print(df.loc[:, 'A'])

0    0.457452
1    0.288725
2   -0.039578
3    0.011836
4   -1.729448
5   -0.367134
Name: A, dtype: float64


In [19]:
# select first 2 rows, specific two columns
print(df.loc[0:1, ['A', 'B']])

          A         B
0  0.457452 -0.664152
1  0.288725 -0.239342


In [20]:
# select specific value
print(df.loc[0, 'A'])

# but "at" is preferred
print(df.at[0, 'A'])

0.457452173994
0.457452173994


### Selection by position (`iloc`)

In [21]:
# specific row (as a Series)
print(df.iloc[3])

A    0.011836
B    0.879879
C    0.872803
D    0.140642
Name: 3, dtype: float64


In [22]:
# specific row (as a sub-table)
print(df.iloc[3:4, :])

          A         B         C         D
3  0.011836  0.879879  0.872803  0.140642


In [23]:
# sub-table
print(df.iloc[3:5, 0:2])

          A         B
3  0.011836  0.879879
4 -1.729448  0.605972


In [24]:
# integer indexing
print(df.iloc[[1,2,4], [0,2]])

          A         C
1  0.288725 -0.475678
2 -0.039578 -0.204653
4 -1.729448  1.955143


### Boolean indexing

In [25]:
# filter only values answering condition in specific column
print(df[df.A > 0])

          A         B         C         D
0  0.457452 -0.664152  0.148900 -1.038054
1  0.288725 -0.239342 -0.475678  0.286864
3  0.011836  0.879879  0.872803  0.140642


In [26]:
# if not using specific column...
print(df[df > 0])

          A         B         C         D
0  0.457452       NaN  0.148900       NaN
1  0.288725       NaN       NaN  0.286864
2       NaN       NaN       NaN  0.837177
3  0.011836  0.879879  0.872803  0.140642
4       NaN  0.605972  1.955143  1.559064
5       NaN  1.795627       NaN  0.907515


# Setting

In [27]:
# set a new column s1
s1 = pd.Series([1,2,3,4,5,6])
df['E'] = s1
print(df)

          A         B         C         D  E
0  0.457452 -0.664152  0.148900 -1.038054  1
1  0.288725 -0.239342 -0.475678  0.286864  2
2 -0.039578 -0.926392 -0.204653  0.837177  3
3  0.011836  0.879879  0.872803  0.140642  4
4 -1.729448  0.605972  1.955143  1.559064  5
5 -0.367134  1.795627 -0.395771  0.907515  6


In [28]:
# set a specific value
df.at[0, 'A'] = 0
print(df)

          A         B         C         D  E
0  0.000000 -0.664152  0.148900 -1.038054  1
1  0.288725 -0.239342 -0.475678  0.286864  2
2 -0.039578 -0.926392 -0.204653  0.837177  3
3  0.011836  0.879879  0.872803  0.140642  4
4 -1.729448  0.605972  1.955143  1.559064  5
5 -0.367134  1.795627 -0.395771  0.907515  6


In [29]:
# set a whole column with numpy
df.loc[:, 'D'] = np.array([5] * len(df))
print(df)

          A         B         C  D  E
0  0.000000 -0.664152  0.148900  5  1
1  0.288725 -0.239342 -0.475678  5  2
2 -0.039578 -0.926392 -0.204653  5  3
3  0.011836  0.879879  0.872803  5  4
4 -1.729448  0.605972  1.955143  5  5
5 -0.367134  1.795627 -0.395771  5  6


In [30]:
# set with boolean indexing
df[df < 0] = np.nan
print(df)

          A         B         C  D  E
0  0.000000       NaN  0.148900  5  1
1  0.288725       NaN       NaN  5  2
2       NaN       NaN       NaN  5  3
3  0.011836  0.879879  0.872803  5  4
4       NaN  0.605972  1.955143  5  5
5       NaN  1.795627       NaN  5  6


# Missing Data

In [31]:
# dropping rows with any missing data (see documentation for more)
df1 = df.copy()
print(df1.dropna(how = 'any'))

          A         B         C  D  E
3  0.011836  0.879879  0.872803  5  4


In [32]:
# filling missing values with a specific value
print(df1.fillna(value = 5))

          A         B         C  D  E
0  0.000000  5.000000  0.148900  5  1
1  0.288725  5.000000  5.000000  5  2
2  5.000000  5.000000  5.000000  5  3
3  0.011836  0.879879  0.872803  5  4
4  5.000000  0.605972  1.955143  5  5
5  5.000000  1.795627  5.000000  5  6


In [33]:
# getting a boolean mask of where missing values are (similar to R)
print(pd.isna(df1))

       A      B      C      D      E
0  False   True  False  False  False
1  False   True   True  False  False
2   True   True   True  False  False
3  False  False  False  False  False
4   True  False  False  False  False
5   True  False   True  False  False


# Basic Operations

In [34]:
# apply mean to each column
print(df.mean())

A    0.100187
B    1.093826
C    0.992282
D    5.000000
E    3.500000
dtype: float64


In [35]:
# apply sum to each row
print(df.sum(axis = 1))

0     6.148900
1     7.288725
2     8.000000
3    10.764519
4    12.561115
5    12.795627
dtype: float64


In [36]:
# df.apply a non-pandas function
print(df.apply(np.cumsum))

          A         B         C   D   E
0  0.000000       NaN  0.148900   5   1
1  0.288725       NaN       NaN  10   3
2       NaN       NaN       NaN  15   6
3  0.300561  0.879879  1.021703  20  10
4       NaN  1.485852  2.976846  25  15
5       NaN  3.281479       NaN  30  21


In [37]:
# apply anonumous function
print(df.apply(lambda x: x.max() - x.min()))

A    0.288725
B    1.189654
C    1.806243
D    0.000000
E    5.000000
dtype: float64


# Basic Manipulation

pandas is inspired by R's `tidyverse` philosophy and works best with "tidy", long datasets, in which every column is a single variable, and every row is a single observation.

In [38]:
# group by a categorical variable, and get mean by group for all numeric variables
df2 = pd.DataFrame({'categorical': np.tile(['A', 'B'], (5, )),
                    'numerical1': np.random.randn(10),
                    'numerical2': 10 + 2 * np.random.randn(10)})
df2.groupby('categorical').mean()

numerical1  numerical2
categorical                        
A             -0.309385    9.885874
B             -0.522445    9.610078

### See more in documentation